[package]
name = "Redundancy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Redundancy"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
regex = "1.10.6"
